---
- name: build VM with Packer
  command: "packer build -var-file {{ item.packer_varfile }} -only=virtualbox-iso {{ item.packer_template }}"
  args:
    chdir: "/home/vagrant/packer-templates"
  environment:
    PATH: "{{ ansible_env.PATH }}:/vagrant/icebox/third_party/virtualbox/out/linux.amd64/release/bin/"
  become: false

- name: get build artifact
  find:
    path: "/home/vagrant/packer-templates/output-virtualbox-iso"
  register: packer_output

- name: import VM in VirtualBox registry
  command: "VBoxManage import {{ packer_output.files[0].path }}"
  args:
    chdir: "/home/vagrant/packer-templates"
  environment:
    PATH: "{{ ansible_env.PATH }}:/vagrant/icebox/third_party/virtualbox/out/linux.amd64/release/bin/"
  become: false

- name: remove output-qemu
  file:
    path: /home/vagrant/packer-templates/output-virtualbox-iso
    state: absent
  